### ISSUE TITLE
[Bug] Resolve Truffle to Weed Bug in function

### ISSUE THREAD

**Issue by WuZhuoran** [WuZhuoran/Stardew_AnimalSitter#11]
This is from previous #9 .

Currently we are using a temp fix that disable one config that caused the bug. It could be great if we could resolve this forever.

This happend bcause we have a config TakeTrufflesFromPigs which will get one Truffle from pig for the first time when you press O. Then this bug happened. I think the root cause line of code is here:

https://github.com/WuZhuoran/Stardew_AnimalSitter/blob/45cf9b0c3d60b701a037827a2633f72c5215ddd4/AnimalSitter/AnimalSitter.cs#L220

**Comment by Mrstraxler** [comment]
Awesome thanks for your time and work and creating this mod!
