### ISSUE TITLE
[Bug] After harvest pigs, they search for weeds instead trouffles

### ISSUE THREAD

**Issue by WuZhuoran** [WuZhuoran/Stardew_AnimalSitter#9]
From this page: https://www.nexusmods.com/stardewvalley/mods/20831?tab=posts

**Comment by Mrstraxler** [comment]
<img width="467" alt="Screenshot 2024-04-02 at 12 24 36 AM" src="https://github.com/WuZhuoran/Stardew_AnimalSitter/assets/165867625/a0b44f10-3b99-49aa-a98c-4ae3f29f8db9">

Heres an image its driving me crazy haha!

**Comment by WuZhuoran** [comment]
> <img alt="Screenshot 2024-04-02 at 12 24 36 AM" width="467" src="https://private-user-images.githubusercontent.com/165867625/319027103-a0b44f10-3b99-49aa-a98c-4ae3f29f8db9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMjU5MTksIm5iZiI6MTcxMjEyNTYxOSwicGF0aCI6Ii8xNjU4Njc2MjUvMzE5MDI3MTAzLWEwYjQ0ZjEwLTNiOTktNDlhYS1hOThjLTRhZTNmMjlmOGRiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QwNjI2NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjI0OGZjMTlkMDBkOTZhOTFhMGU4OWQwNzU3NmRlOTA5Zjg2OGJjZGRmZDUyOTY3ZjVkNGQwOTA2MGVjNDYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gz69kf9MJSIEhNtnMZTpTdxAQZKxbUN_NTwVOxHGCdA">
> Heres an image its driving me crazy haha!

Thanks for your screenshot! I will update the mod ASAP.

**Comment by WuZhuoran** [comment]
> <img alt="Screenshot 2024-04-02 at 12 24 36 AM" width="467" src="https://private-user-images.githubusercontent.com/165867625/319027103-a0b44f10-3b99-49aa-a98c-4ae3f29f8db9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMTc5ODEsIm5iZiI6MTcxMjIxNzY4MSwicGF0aCI6Ii8xNjU4Njc2MjUvMzE5MDI3MTAzLWEwYjQ0ZjEwLTNiOTktNDlhYS1hOThjLTRhZTNmMjlmOGRiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQwODAxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWEzMzAwMzhkNWRhZTZlY2FkOTIzMTY1YjMzYjlkODNjNzZiZGI4MzI2MDljODJmNDIyMmQ3NTEwYzA4N2NjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.19nM2R0PfI5nDngA5JsxN2bKJhRT_GCM9ZEOjzl6Ww8">
> Heres an image its driving me crazy haha!

Hi @Mrstraxler 

I just update version v2.0.4 https://www.nexusmods.com/stardewvalley/mods/20831 It will temporary resolve this issue.

I already root cause this issue. This happend bcause we have a config `TakeTrufflesFromPigs` which will get one Truffle from pig for the first time when you press `O`. Then this bug happened. I think the root cause line of code is here: https://github.com/WuZhuoran/Stardew_AnimalSitter/blob/45cf9b0c3d60b701a037827a2633f72c5215ddd4/AnimalSitter/AnimalSitter.cs#L220

So I just update v2.0.4 which is a temp solution: Disable this config. 

The only disadvantage is that you cannot get a truffle before the pig searched any truffle. (That is reasonable!) 

I will continue working on a fix to make this config workable. Let me know if new version could work or not. Thank!
